micronaut:
  application:
    name: benchmark-animation
  datasource:
    bean-context-initialization: false

datasources:
  default:
    order: 1
    description: HoloDB embedded
    url: 'jdbc:holodb:embedded:resource://holodb.yaml?schema=simulation'
    username: ''
    password: ''
    driverClassName: 'hu.webarticum.holodb.embedded.HoloEmbeddedDriver'
    minimum-idle: 0
    initialization-fail-timeout: -1
