micronaut:
  application:
    name: benchmark-animation
  datasource:
    bean-context-initialization: false

datasources:
  default:
    order: 1
    description: HoloDB embedded
    url: 'jdbc:holodb:embedded:resource://holodb.yaml?schema=simulation'
    username: ''
    password: ''
    driverClassName: 'hu.webarticum.holodb.embedded.HoloEmbeddedDriver'
    minimum-idle: 0
    initialization-fail-timeout: -1

  h2:
    order: 2
    description: H2 in-memory
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    dialect: H2
    schema-generate: CREATE_DROP
    minimum-idle: 0
    initialization-fail-timeout: -1

  sqlite:
    order: 3
    description: SQLite local file
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/tmp/benchmark-animation.sqlite
    username: ""
    password: ""
    schema-generate: NONE
    minimum-idle: 0
    initialization-fail-timeout: -1

  mysql:
    order: 4
    description: MySQL local
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/benchmark_animation
    username: benchmark_animation
    password: benchmark_animation
    dialect: MYSQL
    schema-generate: NONE
    minimum-idle: 0
    initialization-fail-timeout: -1

  postgres:
    order: 5
    description: PostgreSQL local
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/benchmark_animation
    username: benchmark_animation
    password: benchmark_animation
    dialect: POSTGRES
    schema-generate: NONE
    minimum-idle: 0
    initialization-fail-timeout: -1
